<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="102" started-at="2017-06-21T05:24:15Z" finished-at="2017-06-21T05:24:15Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="102" started-at="2017-06-21T05:24:15Z" finished-at="2017-06-21T05:24:15Z">
      <class name="Testcases.fbSignUpTC">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:Testcases.fbSignUpTC@7791a895]" name="beforeTest" is-config="true" duration-ms="0" started-at="2017-06-21T00:24:15Z" finished-at="2017-06-21T00:24:15Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utilities.WDFunctions.maxPage(WDFunctions.java:98)
	at base.configuration.beforeTest(configuration.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:510)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:211)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.beforeRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:616)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="signUp()[pri:0, instance:Testcases.fbSignUpTC@7791a895]" name="signUp" duration-ms="5" started-at="2017-06-21T00:24:15Z" finished-at="2017-06-21T00:24:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method status="SKIP" signature="afterTest()[pri:0, instance:Testcases.fbSignUpTC@7791a895]" name="afterTest" is-config="true" duration-ms="0" started-at="2017-06-21T00:24:15Z" finished-at="2017-06-21T00:24:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- Testcases.fbSignUpTC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
